### PR TITLE
fix(swr): error type is correct even when it's the same type as success type

### LINKED ISSUE #1256: Unknown error type when using duplicate reference
## What are the steps to reproduce this issue?

1. Update swagger to use same schema for 200 as another response code or default in the example app like: https://github.com/anymaniax/orval/compare/master...vonkanehoffen:orval:master
2. Run Orval to regenerate React Query handlers

## What happens?

The generated code now types React Query errors as `unknown`

## What were you expecting to happen?

It should type them as `Pets` right?

## Any logs, error output, etc?

No errors. Output committed to forked repo above.
https://github.com/vonkanehoffen/orval/commit/fb4a59f98b80c7c6bd97f0a0e87c058778e6c3c1

## Any other comments?

I wish I could figure out why this is happening myself 😭 

## What versions are you using?

**Operating System:** MacOS 14.2.1
**Package Version:** 6.25.0
**Browser Version:** N/A

### PR DESCRIPTION
**Pull request by AffeJonsson**
## Status

**READY**

## Description

Fixes #1256 
Problem was that the error type was getting filtered out as it was equal to the success type, resulting in error being unknown.

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Changelog Entry (unreleased)

## Steps to Test or Reproduce

1. cd tests
2. yarn generate:swr
3. check generated/swr/errors/endpoints.ts
4. `export type CreateItemsQueryError = AxiosError<Item>`
5. compared to previous build, where it would be `export type CreateItemsQueryError = AxiosError<unknown>`

### CODE REVIEW

File: packages/core/src/getters/response.ts [hunk 1]
```diff
@@ -37,6 +37,7 @@ export const getResponse = ({
     operationName,
     context,
     'void',
+    (type) => type.key.startsWith('2') + type.value,
```
Comment (melloware) [inline packages/core/src/getters/response.ts:40]: Can `type.key` ever be null?

**Review by melloware — APPROVED** [review]

File: packages/core/src/getters/response.ts (hunk 1 above)
Comment (AllieJonsson) [reply packages/core/src/getters/response.ts:40]: It shouldn't, it comes from `[statuscode: string]` in `ResponsesObject`, which gets picked up from 
```yaml
paths:
  /error:
    post:
      responses:
        '200': 
        # ^
```
So I think this is safe
