### PR TITLE
fix(zod): date format now respects useDates override

### LINKED ISSUE #1402: Zod: type string format date should be "YYYY-MM-DD"
refs. #971

## What are the steps to reproduce this issue?

1. Create a body field with type string and format date
2. generate schema using zod
3. generated date field as `zod.date()`

## What happens?

format date (`type: "string", format: "date"`) is [defined as "YYYY-MM-DD" formatted string in OpenAPI v3 spec](https://spec.openapis.org/registry/format/date)
in zod, `zod.string().date()` means that, but client generated `zod.date()`

## What were you expecting to happen?

`zod.string().date()` should be generated instead of `zod.date()`

# Any other comments?
respect to #971, `zod.date()` should be generated for **both `format: "date"` and `format: "date-time`** when`output.override.useDates` is true.

### PR DESCRIPTION
**Pull request by TommoLeedsy**
## Status

**READY**

## Description

This PR fixes #1402 and respects the `useDates` override when generating the zod specification.

### CODE REVIEW

**Comment by melloware** [comment]
Looks like tests are failing with...

```
Error: generated/zod/circularReferences.ts(30,29): error TS2339: Property 'date' does not exist on type 'ZodString'.
Error: generated/zod/coerce.ts(30,36): error TS2339: Property 'coerce' does not exist on type 'ZodString'.
Error: generated/zod/preprocess.ts(31,29): error TS2339: Property 'date' does not exist on type 'ZodString'.
Error: generated/zod/strict-mode.ts(30,2[9](https://github.com/anymaniax/orval/actions/runs/9276296526/job/25523055915?pr=1406#step:11:10)): error TS2339: Property 'date' does not exist on type 'ZodString'.
```

File: packages/zod/src/index.ts [hunk 1]
```diff
@@ -130,17 +132,24 @@ export const generateZodValidationSchemaDefinition = (
...
+        if (!context.output.override.useDates) {
+          functions.push([type as string, undefined], ['datetime', undefined]);
+        } else {
+          functions.push(['date', undefined]);
+        }
         break;
       }
 
+      functions.push([type as string, undefined]);
+
```
Comment (RyoNkmr) [inline packages/zod/src/index.ts]: looks good to me.
and if i had to say, it can makes this simple to handle `useDates` first like:

```ts
      if (
        context.output.override.useDates &&
        (schema.format === 'date' || schema.format === 'date-time')
      ) {
        functions.push(['date', undefined]);
        break;
      }

      functions.push([type as string, undefined]);

      if (schema.format === 'date') {
        functions.push(['date', undefined]);
        break;
      }

      if (schema.format === 'date-time') {
        functions.push(['datetime', undefined]);
        break;
      }
```

**Review by RyoNkmr — COMMENTED** [review]
thank you(and I'm so sorry)

**Review by melloware — CHANGES_REQUESTED** [review]
See comments from @RyoNkmr

**Comment by TommoLeedsy** [comment]
@melloware @RyoNkmr This should be ready for re-review, all the tests now pass and the requested changes were made.

**Review by melloware — APPROVED** [review]
