### PR TITLE
fix(generator): add prefix to es5keyword parameters

### LINKED ISSUE #350: Bug: parameter names identical to js keywords are not prefixed
```
/method/{default}:
    get:
      parameters:
        - name: default
```

Ends up with `Declaration or statement expected.ts(1128)` in generated file. Because parameter name `default` is not prefixed with `_`

### PR DESCRIPTION
**Pull request by yekver**
## Status

**READY**

## Description
Fix #350

### CODE REVIEW

File: src/core/getters/params.ts [hunk 1]
```diff
@@ -58,7 +58,7 @@ export const getParams = ({
         schema,
       } = pathParam.parameter;
 
-      const name = sanitize(camel(nameWithoutSanitize));
+      const name = sanitize(camel(nameWithoutSanitize), { es5keyword:true });
```
Comment (anymaniax) [inline src/core/getters/params.ts:61]: will remove underscore and dash on the string if you use the sanitize function like this
