### PR TITLE
fix: take optional request body into account when creating form data

### LINKED ISSUE #1392: Non-requred requestBody results in TS error
## What are the steps to reproduce this issue?

1. Get a spec with: (see specs excerpt below)
  - multipart/form-data
  - not-required requestBody 
2. Generate react query api client
3. Observe that the generated code fails TS checks

## What happens?
That piece gets generated:
```
    const formData = new FormData();
    if (parentPictureCreateBody.file !== undefined) {
        formData.append("file", parentPictureCreateBody.file);
    }
```
`parentPictureCreateBody` is possibly undefined, so accessing it with this way results in an error.

## What were you expecting to happen?
Something along these lines to be generated (note the optional chaining)
```
    if (parentPictureCreateBody?.file !== undefined) {
      formData.append("file", parentPictureCreateBody.file);
    }
```

## Any logs, error output, etc?
This is the error that I'm getting
`'parentPictureCreateBody' is possibly 'undefined'.ts(18048)`
…

## Any other comments?
I've been able to trace it back to [this line](https://github.com/anymaniax/orval/blob/c1adaf78f99b5a8e23bd17f44fa7b843b8b5524d/packages/core/src/getters/res-req-types.ts#L355), but I know far to little about this project to even propose a MR. The only thing coming to my mind is adding optional chainig parameter, but that feels hacky and very short sighted.

```
return acc + `if(${valueKey} !== undefined) {\n ${formDataValue} }\n`;
```
to
```
return acc + `if(${valueKey.replace(/./g, '?.')} !== undefined) {\n ${formDataValue} }\n`;
```

It wasn't occuring until version `6.26.0`, I suspect due to that the requestBody was always marked as required. Occurs in `6.29.1`.

## What versions are you using?

**Operating System:** Manjaro 23.1.4
**Package Version:** 6.29.1 (see commend above)
**Browser Version:** Brave Version 1.65.126 Chromium: 124.0.6367.118 (Official Build) (64-bit)

### Specs excerpt
```
"/api/parent/{parent}/pictures": {
      "post": {
        "operationId": "parent_picture_create",
        "tags": ["ParentPicture"],
        "responses": {
          "201": {
            "description": "ParentPicture resource created",
            "content": {
              "application/ld+json": {
                "schema": {
                  "$ref": "#/components/schemas/ParentPicture.jsonld-media_object.read"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ParentPicture-media_object.read"
                }
              },
              "application/pdf": {
                "schema": {
                  "$ref": "#/components/schemas/ParentPicture-media_object.read"
                }
              },
              "multipart/form-data": {
                "schema": {
                  "$ref": "#/components/schemas/ParentPicture-media_object.read"
                }
              }
            },
            "links": {}
          },
          "400": {
            "description": "Invalid input"
          },
          "422": {
            "description": "Unprocessable entity"
          }
        },
        "summary": "Creates a ParentPicture resource.",
        "description": "Creates a ParentPicture resource.",
        "parameters": [
          {
            "name": "parent",
            "in": "path",
            "description": "Parent identifier",
            "required": true,
            "deprecated": false,
            "allowEmptyValue": false,
            "schema": {
              "type": "integer"
            },
            "style": "simple",
            "explode": false,
            "allowReserved": false
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "file": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          },
          "required": false
        },
        "deprecated": false
      },
      "parameters": []
    },
```

### PR DESCRIPTION
**Pull request by AffeJonsson**
## Status

**READY**

## Description

Fixes #1392 
This makes sure to check for undefined in case the request body is optional. This also contains changes to not cast to `any` when handling subtypes.

Before:
```ts
export const createPets = (
  pet?: Pet,
  version: number = 1,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Pet>> => {
  const formData = new FormData();
  if ((pet as any).name !== undefined) {
    formData.append('name', (pet as any).name);
  }
  if ((pet as any).tag !== undefined) {
    formData.append('tag', (pet as any).tag);
  }

  if ((pet as any).id !== undefined) {
    formData.append('id', (pet as any).id.toString());
  }
  if ((pet as any).name !== undefined) {
    formData.append('name', (pet as any).name);
  }
  if ((pet as any).tag !== undefined) {
    formData.append('tag', (pet as any).tag);
  }
  if (pet['@id'] !== undefined) {
    formData.append('@id', pet['@id']);
  }
  if (pet.email !== undefined) {
    formData.append('email', pet.email);
  }
  if (pet.callingCode !== undefined) {
    formData.append('callingCode', pet.callingCode);
  }
  if (pet.country !== undefined) {
    formData.append('country', pet.country);
  }

  return axios.post(`/v${version}/pets`, formData, options);
};
```
After:
```ts
export const createPets = (
  pet?: Pet,
  version: number = 1,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Pet>> => {
  const formData = new FormData();
  const petPetBase = pet as PetBase | undefined;
  if (petPetBase?.name !== undefined) {
    formData.append('name', petPetBase.name);
  }
  if (petPetBase?.tag !== undefined) {
    formData.append('tag', petPetBase.tag);
  }

  const petPetExtended = pet as PetExtended | undefined;
  if (petPetExtended?.id !== undefined) {
    formData.append('id', petPetExtended.id.toString());
  }
  if (petPetExtended?.name !== undefined) {
    formData.append('name', petPetExtended.name);
  }
  if (petPetExtended?.tag !== undefined) {
    formData.append('tag', petPetExtended.tag);
  }
  if (pet?.['@id'] !== undefined) {
    formData.append('@id', pet['@id']);
  }
  if (pet?.email !== undefined) {
    formData.append('email', pet.email);
  }
  if (pet?.callingCode !== undefined) {
    formData.append('callingCode', pet.callingCode);
  }
  if (pet?.country !== undefined) {
    formData.append('country', pet.country);
  }

  return axios.post(`/v${version}/pets`, formData, options);
};
```

## Todos

- [x] Tests
- [ ] Documentation
- [ ] Changelog Entry (unreleased)

## Steps to Test or Reproduce

generate:react-query
generate:swr

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by AffeJonsson** [comment]
Noticed the cast to subtype only worked if mocks were generated, I'll fix a commit where they are imported properly

**Review by melloware — DISMISSED** [review]

File: packages/core/src/getters/res-req-types.ts [hunk 1]
```diff
@@ -87,35 +87,45 @@ export const getResReqTypes = (
           ] as ResReqTypesValue[];
         }
 
-        const formData = isFormData
+        const [formData, additionalFormDataImports] = isFormData
```
Comment (soartec-lab) [inline packages/core/src/getters/res-req-types.ts]: If there are multiple return types, the responsibility for the function will no longer be single. And readability also decreases.

If possible, I would like to separate each function and separate the methods for obtaining `formData` and `additionalFormDataImports`.What do you think?

**Review by soartec-lab — COMMENTED** [review]
@AffeJonsson 
I have consulted with you about how to extend the function, so please check it out.

File: packages/core/src/getters/res-req-types.ts (hunk 1 above)
Comment (AllieJonsson) [reply packages/core/src/getters/res-req-types.ts]: @soartec-lab  Good idea. Please see new commit!

**Review by soartec-lab — APPROVED** [review]
Thanks !
