### PR TITLE
fix: remove unnecessary empty item in case of null-only enum or empty enum (#1022)

### LINKED ISSUE #1022: Invalid type files are generated with Null-only enum or Empty enum
## What are the steps to reproduce this issue?

1. input this
```yaml
# openapi.yaml
openapi: 3.0.0
info:
  title: title
components:
  schemas:
    NullOnlyStringEnum:
      type: string
      nullable: true
      enum:
        - null
    NullOnlyNumberEnum:
      type: number
      nullable: true
      enum:
        - null
    EmptyStringEnum:
      type: string
      enum: []
    EmptyNumberEnum:
      type: number
      enum: []
```
2. generate
`npx orval --input ./openapi.yaml --output out.ts`
3. output
```ts
/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * title
 */
export type EmptyNumberEnum = typeof EmptyNumberEnum[keyof typeof EmptyNumberEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EmptyNumberEnum = {
  '': , // invalid typescript
} as const;

export type EmptyStringEnum = typeof EmptyStringEnum[keyof typeof EmptyStringEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EmptyStringEnum = {
  '': '', // valid typescript, but not appropriate
} as const;

export type NullOnlyNumberEnum = typeof NullOnlyNumberEnum[keyof typeof NullOnlyNumberEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NullOnlyNumberEnum = {
  '': , // invalid typescript
  null: null,
} as const;

export type NullOnlyStringEnum = typeof NullOnlyStringEnum[keyof typeof NullOnlyStringEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NullOnlyStringEnum = {
  '': '', // valid typescript, but not appropriate
  null: null,
} as const;
```

## What happens?
An empty enum item not included in spec is generated.
In case of number, a const value is empty and it's invalid typescript.

## What were you expecting to happen?

output
```ts
/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * title
 */
export type EmptyNumberEnum = typeof EmptyNumberEnum[keyof typeof EmptyNumberEnum]; // or, never


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EmptyNumberEnum = {} as const;

export type EmptyStringEnum = typeof EmptyStringEnum[keyof typeof EmptyStringEnum]; // or, never


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EmptyStringEnum = {} as const;

export type NullOnlyNumberEnum = typeof NullOnlyNumberEnum[keyof typeof NullOnlyNumberEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NullOnlyNumberEnum = {
  null: null,
} as const;

export type NullOnlyStringEnum = typeof NullOnlyStringEnum[keyof typeof NullOnlyStringEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NullOnlyStringEnum = {
  null: null,
} as const;
```

## Any logs, error output, etc?
No information logs involving the behavior.

```
🍻 Start orval v6.19.1 - A swagger client generator for typescript
⚠️  SyntaxError: /Users/mitsurukasai/Documents/exercise/orval-ref-decode/openapi.yaml is not a valid Openapi API definition
🎉 title - Your OpenAPI spec has been converted into ready to use orval!
```

## Any other comments?

Thanks for developing and maintaining this awesome package! :D

I try to make PR about this issue.

## What versions are you using?

**Operating System:** MacOS 13.0
**Package Version:** 6.19.1
**Browser Version:** N/A

### PR DESCRIPTION
**Pull request by bigen1925**
## Status

**READY**

## Description
Remove unnecessary empty item in case of null-only enum or empty enum.

Close #1022

## Related PRs
The issue in case of empty enum may exist before.

The issue in case of null-only enum is occured by this PR.

Because null is filtered, null-only enum is handled as empty enum.

| branch              | PR       |
| ------------------- | -------- |
| [alanpoulain:fix/null-enum](https://github.com/alanpoulain/orval/tree/fix/null-enum) | [link](https://github.com/anymaniax/orval/pull/928/files) |

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Changelog Entry (unreleased)

## Steps to Test or Reproduce

Added specification and confirmed generated type files.

### CODE REVIEW

File: packages/core/src/getters/scalar.ts [hunk 1]
```diff
@@ -84,12 +86,12 @@ export const getScalar = ({
...
-        value = `'${enumItems
-          .map((enumItem: string) =>
-            isString(enumItem) ? escape(enumItem) : `${enumItem}`,
+        value = `${enumItems
+          .map((enumItem: string | null) =>
+            isString(enumItem) ? `'${escape(enumItem)}'` : `${enumItem}`,
           )
           .filter(Boolean)
-          .join(`' | '`)}'`;
+          .join(` | `)}`;
```
Comment (bigen1925) [inline packages/core/src/getters/scalar.ts:94]: To avoid that `null` is quoted like `'null'`

File: packages/core/src/getters/scalar.ts [hunk 2]
```diff
@@ -131,12 +133,12 @@ export const getScalar = ({
...
-        const value = `'${enumItems
-          .map((enumItem: string) =>
-            isString(enumItem) ? escape(enumItem) : `${enumItem}`,
+        const value = `${enumItems
+          .map((enumItem: unknown) =>
+            isString(enumItem) ? `'${escape(enumItem)}'` : `${enumItem}`,
           )
           .filter(Boolean)
-          .join(`' | '`)}'`;
+          .join(` | `)}`;
```
Comment (bigen1925) [inline packages/core/src/getters/scalar.ts:141]: This code can not handle array enum, or object enum.

output is like 
```ts
export const ObjectEnum = {
  '[object_Object]': [object Object],
} as const;
```

I didn't fix because not relevant the issue, but should I leave `FIXME` comment?

File: tests/configs/default.config.ts [hunk 3]
```diff
@@ -64,13 +64,6 @@ export default defineConfig({
       target: '../generated/default/null-type-v3-0/endpoints.ts',
     },
   },
-  'nullable-enum': {
```
Comment (bigen1925) [inline tests/configs/default.config.ts:67]: I migrated cases in `nullable-enum` to `null-type-v3-0`

File: tests/specifications/nullable-enum.yaml [hunk 4]
```diff
@@ -1,66 +0,0 @@
-openapi: 3.0.0
```
Comment (bigen1925) [inline tests/specifications/nullable-enum.yaml:1]: migrated to `null-type-v3-0.yaml`

**Comment by bigen1925** [comment]
Before
```ts
export type NullOnlyNumberEnum = typeof NullOnlyStringEnum[keyof typeof NullOnlyStringEnum] | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NullOnlyStringEnum = {
  '': ,
} as const;

export type NullOnlyStringEnum = typeof NullOnlyStringEnum[keyof typeof NullOnlyStringEnum] | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NullOnlyStringEnum = {
  '': '',
} as const;
```

After
```ts
export type NullOnlyNumberEnum = typeof NullOnlyStringEnum[keyof typeof NullOnlyStringEnum] | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NullOnlyStringEnum = {
} as const;

export type NullOnlyStringEnum = typeof NullOnlyStringEnum[keyof typeof NullOnlyStringEnum] | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NullOnlyStringEnum = {
} as const;
```

**Comment by bigen1925** [comment]
Ideally, it is desirable that like this code is generated
```
export type NullOnlyNumberEnum = null;
export type NullOnlyStringEnum = null;
export type EmptyEnum = never;
```
, but I think program will get too complex considering combine schema.

Because this is never
```
const EmptyObject = {} as const
typeof EmptyObject [keyof typeof EmptyObject] // never

```
, so meaning is the same.

File: packages/core/src/getters/scalar.ts (hunk 2 above)
Comment (melloware) [reply packages/core/src/getters/scalar.ts:141]: up to you if you want to leave a FIXME but not necessary?

**Review by melloware — APPROVED** [review]

File: packages/core/src/getters/scalar.ts (hunk 2 above)
Comment (bigen1925) [reply packages/core/src/getters/scalar.ts:141]: @melloware thanks for your review, and sorry for late reply.

I don't think necessary while someone report an issue.
