### PR TITLE
fix: uppercase method verbs

### LINKED ISSUE #888: HTTP PATCH case sensitivity
## What are the steps to reproduce this issue?

1. Have an openAPI spec that has a PATCH object
2. Don't use axios (because axios auto-solves this issue)
3. Generate a client

## What happens?

The client will be generated with a lowercase "patch" method. ie:

```js
{
      url: `...`,
      method: "patch",
      data: patchBody,
}
```

## What were you expecting to happen?

Since patch is the only standard HTTP method that is case sensitive, it should result in a method of `PATCH`.

## Any logs, error output, etc?

N/A

## Any other comments?

For more details on this, see https://blog.k-nut.eu/patch-capitalization and the [HTTP standard normalization section](https://fetch.spec.whatwg.org/#concept-method-normalize)

## What versions are you using?

**Operating System:** Mac OS Ventura 13.4
**Package Version:** 6.16.0
**Browser Version:** Chrome 114.0.5735.198

### PR DESCRIPTION
**Pull request by melloware**
## Status

Fix #888 

Bare minimum change and least invasive to uppercase the Axios method like...

```js
method: 'GET'
```

### CODE REVIEW

File: packages/core/src/utils/assertion.ts [hunk 1]
```diff
@@ -81,5 +80,11 @@ export const isRootKey = (specKey: string, target: string) => {
...
 
 export const isUrl = (str: string) => {
-  return validatorIsUrl(str, { require_tld: false });
+  let givenURL;
+  try {
+    givenURL = new URL(str);
+  } catch (error) {
+    return false;
+  }
+  return givenURL.protocol === 'http:' || givenURL.protocol === 'https:';
```
Comment (melloware) [inline packages/core/src/utils/assertion.ts:89]: This is in another PR but without this right now the tests won't pass.

**Review by anymaniax — APPROVED** [review]
